### ISSUE TITLE
Check board against Ordbok-API

### ISSUE THREAD

**Issue by amunds1** [amunds1/5x5game-masterthesis#19]
[Checking of game board flow in draw.io](https://app.diagrams.net/#G1SICuK31y19zsY9V3t4wOSAJWO4ecDChj)

Use the [Ordbok-API](https://ord.uib.no/ord_2_API.html) to check for valid words on the game board

**Optimizations**
1. Only check for valid words in the affected row and column
2. Only check for valid words after the letter change. For instance, if the player changes WATER to WATAR on the board, do not check WA, because this is not changed
3. Hashmap (stored either in localStorage or Firebase) of previously checked words, which can be queried first

**TODO General**
- [x] Determine where code should be executed, either using Cloud Functions or NextJS API routes
- [x] Figure out a way to store which columns and rows was affected with a letter change. This way the code responsible for checking the board does not have to calculate this

**TODO Client**
- [x] Send row and column data to server
- [x] Update to new game model (/games and /game/new)

**TODO Server**
- [x] Endpoint to receive row and column data from the client
- [x] Check word against Ordbok-API
- [x] Update points in Firebase
- [x] Update board in Firebase
- [x] Return row and/or column with valid word

**Comment by amunds1** [comment]
![image](https://user-images.githubusercontent.com/5740172/192774367-16dba217-b218-4680-9acc-25daf9cd8ca2.png)
