### ISSUE TITLE
Firebase: Start a game with another user

### ISSUE THREAD

**Issue by amunds1** [amunds1/5x5game-masterthesis#21]
Ability to create a game with another authenticated user

**TODO**
- [x] Create a new document in the `games` collection, with a starter board and a document reference to both users in Firebase
- [x] Update `games` array inside each user document with a document reference to the given game
- [x] Select users from a dropdown to play with
- [x] Ability to propose a game to another user
- [x] Only allow the player offered a game to accept
- [x] Ability to withdraw a game proposal
- [x] Store timestamp when game was proposed
- [x] Reject proposed game
