### ISSUE TITLE
Firebase: Connection, database structure and basic functionality

### ISSUE THREAD

**Issue by amunds1** [amunds1/5x5game-masterthesis#22]
Add connection middleware, database structure and basic functionality

**TODO**
- [x] List games for a given user (/games)
- [x] Display opponent name 
- [x] Dedicated page for a given game (/game/[id])
- [x] Basic withConverter for User and Game
- [x] Sign in using GitHub
- [x] Sign out
- [x] Types for User and Game documents
- [x] Ability to see if a user is currently signed in

**Comment by amunds1** [comment]
NextJS prerender error in [GameID].tsx:
- https://stackoverflow.com/questions/71002100/nextjs-prerender-error-works-fine-in-dev-breaks-in-build
- https://stackoverflow.com/questions/61040790/userouter-withrouter-receive-undefined-on-query-in-first-render
